# Generated by Django 3.1.5 on 2021-03-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='itemjson',
        ),
    ]
