# Generated by Django 3.1.5 on 2021-03-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210320_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemjson',
            new_name='item_json',
        ),
    ]
