# Generated by Django 3.1.5 on 2021-04-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210413_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
